### ISSUE TITLE
Error occurred when complile under OS X

### ISSUE THREAD

**Issue by nonew** [T-Rex/wxModularApp#2]
Dear T-Rex,
I followed guide in readme to build demo on OS X 10.10.3, but when I run cmake, the following error occurred:
xxMacBook-Pro:Mac Kevin$ cmake ../ -G "Xcode"
-- The C compiler identification is AppleClang 6.1.0.6020049
-- The CXX compiler identification is AppleClang 6.1.0.6020049
-- Check for working C compiler using: Xcode
-- Check for working C compiler using: Xcode -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Xcode
-- Check for working CXX compiler using: Xcode -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find wxWidgets (missing: wxWidgets_FOUND)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.2/Modules/FindwxWidgets.cmake:870 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:50 (find_package)

-- Configuring incomplete, errors occurred!

I downloaded latest WxWidgets source code 3.0.2 to my "Downloads" folder, and I can open XCode to build minimal sample. Could you help me out of here. Thank you!

**Comment by T-Rex** [comment]
Hi. Before generating the project files using the latest wxWidgets you need to edit the file /Applications/CMake.app/Contents/share/cmake-3.2/Modules/FindwxWidgets.cmake
There you should add support of wxWidgets 3.1. Just search for text `30` and add the same line with `31` (there should be 4 places for this I think). After that CMake will be able to find the latest wxWidgets.
Also, have you compiled wxWIdgets and installed it using `make install` command? Does the script `wx-config --cxxflags` and `wx-config --libs` work when you execute it from command line?

**Comment by T-Rex** [comment]
Did you manage to solve this on your side?
