### ISSUE TITLE
Building Under Linux

### ISSUE THREAD

**Issue by mtangoo** [T-Rex/wxModularApp#3]
For me it didn't work out of the box. I had 2.8 on path so wx-config was wrong one. This one I solved by exporting path
```bash
 export PATH=/home/stefano/wxwidgets:$PATH
```
so that wx3 would overshadow wx28

Then stdwx.h was not found. so I had to run 
```bash
make -I ../../include/
```
I hope the last stage means a bug in CMake Config. is that so?

**Comment by T-Rex** [comment]
Hi. As for problem with wx-config - this is mostly related to your system's configuration.
Regarding the `include` folder: the path to this folder is added in `build\CMakeLists.txt` at line 94 ( 'set(BASE_INCLUDE_DIRECTORIES ${PROJECT_ROOT_DIR}/include)' ). I will check again by myself but looks strange.
